import { execFile } from "node:child_process";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { parseSimpleYaml } from "../src/core/yaml.js";

const scriptPath = fileURLToPath(import.meta.url);
const repoRoot = path.resolve(path.dirname(scriptPath), "..");
const harnessBin = path.join(repoRoot, "bin", "harness.js");
const tempBase = process.env.HARNESS_SMOKE_TMP || os.tmpdir();
const ordinaryOpencodeProject = path.join(tempBase, `harness-self-smoke-opencode-${process.pid}`);
const ordinaryFullOpencodeProject = path.join(tempBase, `harness-self-smoke-opencode-full-${process.pid}`);
const advancedOpencodeCommands = [
  "harness-feature.md",
  "harness-bugfix.md",
  "harness-refactor.md",
  "harness-context.md",
  "harness-status.md",
  "harness-continue.md"
];
const templateOpencodePath = (...segments) => ["templates", "opencode", ...segments].join("/");
const selfOpencodeFiles = [
  "opencode.jsonc",
  ".opencode/README.md",
  ".opencode/commands/harness-self-init.md",
  ".opencode/commands/harness-self-review.md",
  ".opencode/commands/harness-self-test.md",
  ".opencode/agents/harness-framework-planner.md",
  ".opencode/agents/harness-framework-reviewer.md"
];
const mirrorChecks = [
  {
    source: templateOpencodePath("commands", "harness-feature.md"),
    target: ".opencode/commands/harness-feature.md"
  },
  {
    source: templateOpencodePath("commands", "harness-incident.md"),
    target: ".opencode/commands/harness-incident.md"
  },
  {
    source: templateOpencodePath("agents", "validators", "generic-fallback.md"),
    target: ".opencode/agents/validators/generic-fallback.md"
  }
];

try {
  const expectedMirrorFiles = await getExpectedMirrorFiles();
  const initOutput = await harness("self", "init");
  assertIncludes(initOutput, "mode: dry-run");
  assertIncludes(initOutput, ".harness/self/README.md");
  assertIncludes(initOutput, "note: use --apply");

  const beforeRelevantOpencode = await readExistingFiles([...selfOpencodeFiles, ...expectedMirrorFiles]);
  const beforeTemplateAgents = await fs.readFile(path.join(repoRoot, "templates", "AGENTS.md"), "utf8");
  const beforeTemplateOpencode = await snapshotDirectory(path.join(repoRoot, "templates", "opencode"));
  const beforeSkills = await snapshotDirectory(path.join(repoRoot, "skills"));

  const selfOpencodeDryRun = await harness("self", "init", "--with-opencode");
  assertIncludes(selfOpencodeDryRun, "mode: dry-run");
  assertIncludes(selfOpencodeDryRun, ".opencode/agents/harness-framework-planner.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/commands/harness-self-init.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/agents/harness-builder.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/agents/harness-planner.md");
  assertIncludes(selfOpencodeDryRun, ".opencode/commands/harness-feature.md");
  assertSameFileSnapshot(beforeRelevantOpencode, await readExistingFiles([...selfOpencodeFiles, ...expectedMirrorFiles]), "self init --with-opencode dry-run must not write files");

  const selfOpencodeApply = await harness("self", "init", "--apply", "--with-opencode");
  assertIncludes(selfOpencodeApply, "mode: write");
  assertIncludes(selfOpencodeApply, ".opencode/README.md");
  assertIncludes(selfOpencodeApply, ".opencode/agents/harness-builder.md");
  assertIncludes(selfOpencodeApply, ".opencode/commands/harness-feature.md");
  for (const relative of [...selfOpencodeFiles, ...expectedMirrorFiles]) {
    assert(await pathExists(path.join(repoRoot, relative)), `${relative} must be generated by self init --apply --with-opencode`);
  }
  assert(await pathExists(path.join(repoRoot, ".harness", "model-profiles.yml")), "self init --apply --with-opencode must ensure .harness/model-profiles.yml");
  assert(await pathExists(path.join(repoRoot, ".harness", "self", "README.md")), "self init --apply --with-opencode must ensure .harness/self/README.md");
  const gitignoreContent = await fs.readFile(path.join(repoRoot, ".gitignore"), "utf8");
  assertIncludes(gitignoreContent, ".harness-self/");

  for (const check of mirrorChecks) {
    assert((await readRelative(check.target)) === (await readRelative(check.source)), `${check.target} must exactly mirror ${check.source}`);
  }

  const selfOpencodeReadme = await readRelative(".opencode/README.md");
  assertIncludes(selfOpencodeReadme, "must not be edited directly");
  assertIncludes(selfOpencodeReadme, "Edit `templates/opencode/**` instead");

  const selfReviewer = await readRelative(".opencode/agents/harness-framework-reviewer.md");
  assertIncludes(selfReviewer, "model: opencode-go/glm-5.1");

  const selfProfiles = parseSimpleYaml(await readRelative(".harness/model-profiles.yml"));
  const mirroredBuilder = await readRelative(".opencode/agents/harness-builder.md");
  assertIncludes(mirroredBuilder, `model: ${selfProfiles.profiles?.think?.default}`);
  assertExcludes(mirroredBuilder, "{{MODEL_PROFILE_");

  assert((await fs.readFile(path.join(repoRoot, "templates", "AGENTS.md"), "utf8")) === beforeTemplateAgents, "self OpenCode init must not modify templates/AGENTS.md");
  assertSameFileSnapshot(beforeTemplateOpencode, await snapshotDirectory(path.join(repoRoot, "templates", "opencode")), "self OpenCode init must not modify templates/opencode sources");
  assertSameFileSnapshot(beforeSkills, await snapshotDirectory(path.join(repoRoot, "skills")), "self OpenCode init must not modify skills");

  const doctorOutput = await harness("self", "doctor");
  assertIncludes(doctorOutput, "PASS  root AGENTS.md exists");
  assertIncludes(doctorOutput, "PASS  .harness/self/README.md exists");
  assertIncludes(doctorOutput, "PASS  .harness/model-profiles.yml exists");
  assertIncludes(doctorOutput, "PASS  .harness-self/ is ignored");
  assertIncludes(doctorOutput, "PASS  opencode.jsonc exists");
  assertIncludes(doctorOutput, "PASS  .opencode/commands/harness-self-test.md exists");
  assertIncludes(doctorOutput, "PASS  .opencode/agents/harness-framework-reviewer.md exists");
  assertIncludes(doctorOutput, "PASS  .opencode/agents/harness-planner.md matches templates/opencode/agents/harness-planner.md");
  assertIncludes(doctorOutput, "PASS  .opencode/commands/harness-feature.md matches templates/opencode/commands/harness-feature.md");

  await assertDoctorFailsForMissingSelfOpencodeFile();
  await assertDoctorFailsForUnresolvedPlaceholder();
  await assertMirrorDriftDetected();
  await assertMissingMirrorDetected();
  await assertLocalSelfModelProfilesPreservedAndRendered();
  await assertMirrorResyncFromTemplateSource();
  await assertOrdinaryOpencodeInitDoesNotInstallSelfFiles();
  await assertOrdinaryFullOpencodeInitRetainsAdvancedCommands();

  const templateAgents = await fs.readFile(path.join(repoRoot, "templates", "AGENTS.md"), "utf8");
  assertExcludes(templateAgents, "HARNESS_SELF_POLICY");
  assertExcludes(templateAgents, ".harness-self");
  assertSameFileSnapshot(beforeTemplateOpencode, await snapshotDirectory(path.join(repoRoot, "templates", "opencode")), "self smoke must restore templates/opencode sources after resync test");

  const testOutput = await harness("self", "test");
  assertIncludes(testOutput, "Harness Self Test");
  assertIncludes(testOutput, "PASS  target-empty manifest exists");
  assertIncludes(testOutput, "PASS  target-existing-agents local AGENTS.md content preserved");
  assertIncludes(testOutput, "PASS  target-conflict-managed-block local content preserved");
  assertIncludes(testOutput, "PASS  target-conflict-managed-block sync dry-run preserves AGENTS.md");
  assertIncludes(testOutput, "PASS  target-old-manifest reports missing managed AGENTS.md");
  assertIncludes(testOutput, "PASS  templates/AGENTS.md remains free of self rules");
  assertIncludes(testOutput, "sandbox:");

  console.log("self-smoke: PASS");
} finally {
  await fs.rm(ordinaryOpencodeProject, { recursive: true, force: true });
  await fs.rm(ordinaryFullOpencodeProject, { recursive: true, force: true });
}

async function harness(...args) {
  return exec(process.execPath, [harnessBin, ...args], repoRoot);
}

async function exec(command, args, cwd) {
  return new Promise((resolve, reject) => {
    execFile(command, args, { cwd, encoding: "utf8" }, (error, stdout, stderr) => {
      if (error) {
        error.message = `${error.message}\nstdout:\n${stdout}\nstderr:\n${stderr}`;
        reject(error);
        return;
      }
      resolve(stdout);
    });
  });
}

async function harnessAllowFailure(...args) {
  return execAllowFailure(process.execPath, [harnessBin, ...args], repoRoot);
}

async function execAllowFailure(command, args, cwd) {
  return new Promise((resolve) => {
    execFile(command, args, { cwd, encoding: "utf8" }, (error, stdout, stderr) => {
      resolve({ code: error?.code ?? 0, stdout, stderr });
    });
  });
}

async function assertDoctorFailsForMissingSelfOpencodeFile() {
  const relative = ".opencode/commands/harness-self-test.md";
  const absolute = path.join(repoRoot, relative);
  const backup = `${absolute}.self-smoke-bak`;
  await fs.rename(absolute, backup);
  try {
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a required self OpenCode file is missing");
    assertIncludes(result.stdout, `FAIL  ${relative} missing`);
  } finally {
    await fs.rename(backup, absolute);
  }
}

async function assertMirrorDriftDetected() {
  const mirror = ".opencode/agents/harness-planner.md";
  const absolute = path.join(repoRoot, mirror);
  const original = await fs.readFile(absolute, "utf8");
  try {
    await fs.writeFile(absolute, `${original}\nDrifted locally.\n`, "utf8");
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror file drifts");
    assertIncludes(result.stdout, `${mirror} drifted from ${templateOpencodePath("agents", "harness-planner.md")}`);
    assertIncludes(result.stdout, "Edit templates/opencode/** instead, then rerun harness self init --apply --with-opencode.");
  } finally {
    await fs.writeFile(absolute, original, "utf8");
  }
}

async function assertMissingMirrorDetected() {
  const mirror = ".opencode/commands/harness-feature.md";
  const absolute = path.join(repoRoot, mirror);
  const backup = `${absolute}.self-smoke-bak`;
  await fs.rename(absolute, backup);
  try {
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror file is missing");
    assertIncludes(result.stdout, `${mirror} missing; mirror drift from ${templateOpencodePath("commands", "harness-feature.md")}`);
    assertIncludes(result.stdout, "Edit templates/opencode/** instead, then rerun harness self init --apply --with-opencode.");
  } finally {
    await fs.rename(backup, absolute);
  }
}

async function assertMirrorResyncFromTemplateSource() {
  const source = templateOpencodePath("agents", "harness-planner.md");
  const target = ".opencode/agents/harness-planner.md";
  const sourceAbsolute = path.join(repoRoot, source);
  const targetAbsolute = path.join(repoRoot, target);
  const originalSource = await fs.readFile(sourceAbsolute, "utf8");
  const modifiedSource = `${originalSource}\n<!-- self-smoke template resync -->\n`;
  try {
    await fs.writeFile(sourceAbsolute, modifiedSource, "utf8");
    const output = await harness("self", "init", "--apply", "--with-opencode");
    assertIncludes(output, target);
    assertIncludes(await fs.readFile(targetAbsolute, "utf8"), "<!-- self-smoke template resync -->");
  } finally {
    await fs.writeFile(sourceAbsolute, originalSource, "utf8");
    await harness("self", "init", "--apply", "--with-opencode");
    assertExcludes(await fs.readFile(targetAbsolute, "utf8"), "<!-- self-smoke template resync -->");
  }
}

async function assertLocalSelfModelProfilesPreservedAndRendered() {
  const profilesRelative = ".harness/model-profiles.yml";
  const builderRelative = ".opencode/agents/harness-builder.md";
  const profilesAbsolute = path.join(repoRoot, profilesRelative);
  const builderAbsolute = path.join(repoRoot, builderRelative);
  const originalProfiles = await fs.readFile(profilesAbsolute, "utf8");
  const originalBuilder = await fs.readFile(builderAbsolute, "utf8");
  const overriddenProfiles = originalProfiles.replace('default: "openai/gpt-5.5"', 'default: "self/smoke-think"');
  try {
    await fs.writeFile(profilesAbsolute, overriddenProfiles, "utf8");
    const output = await harness("self", "init", "--apply", "--with-opencode");
    assertIncludes(output, "skip-project-local: .harness/model-profiles.yml");
    assert((await fs.readFile(profilesAbsolute, "utf8")) === overriddenProfiles, ".harness/model-profiles.yml local edits must be preserved by self init");
    assertIncludes(await fs.readFile(builderAbsolute, "utf8"), "model: self/smoke-think");
  } finally {
    await fs.writeFile(profilesAbsolute, originalProfiles, "utf8");
    await fs.writeFile(builderAbsolute, originalBuilder, "utf8");
    await harness("self", "init", "--apply", "--with-opencode");
  }
}

async function assertDoctorFailsForUnresolvedPlaceholder() {
  const relative = ".opencode/agents/harness-builder.md";
  const absolute = path.join(repoRoot, relative);
  const original = await fs.readFile(absolute, "utf8");
  try {
    await fs.writeFile(absolute, original.replace(/^model: .*$/m, "model: {{MODEL_PROFILE_THINK}}"), "utf8");
    const result = await harnessAllowFailure("self", "doctor");
    assert(result.code !== 0, "self doctor must fail when a mirror keeps unresolved placeholders");
    assertIncludes(result.stdout, `${relative} still contains unresolved MODEL_PROFILE placeholders`);
  } finally {
    await fs.writeFile(absolute, original, "utf8");
  }
}

async function assertOrdinaryOpencodeInitDoesNotInstallSelfFiles() {
  await fs.rm(ordinaryOpencodeProject, { recursive: true, force: true });
  const output = await harness("init", "--project", ordinaryOpencodeProject, "--auto", "--with-opencode");
  assertIncludes(output, "new-managed: .opencode/commands/harness.md");
  assertIncludes(output, "new-managed: .opencode/agents/harness-planner.md");
  assert(await pathExists(path.join(ordinaryOpencodeProject, "opencode.jsonc")), "ordinary init --with-opencode must still generate opencode.jsonc");
  assert(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "agents", "harness-planner.md")), "ordinary init must still generate template agent files");
  assert(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "harness.md")), "ordinary init must install the minimal builder command by default");
  const ordinaryBuilder = await fs.readFile(path.join(ordinaryOpencodeProject, ".opencode", "agents", "harness-builder.md"), "utf8");
  assertIncludes(ordinaryBuilder, "model: openai/gpt-5.5");
  assertExcludes(ordinaryBuilder, "{{MODEL_PROFILE_THINK}}");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "harness-feature.md"))), "ordinary init minimal default must not install advanced feature command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "harness-self-init.md"))), "ordinary init must not install self command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "harness-self-review.md"))), "ordinary init must not install self review command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "commands", "harness-self-test.md"))), "ordinary init must not install self test command files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "agents", "harness-framework-planner.md"))), "ordinary init must not install self planner agent files");
  assert(!(await pathExists(path.join(ordinaryOpencodeProject, ".opencode", "agents", "harness-framework-reviewer.md"))), "ordinary init must not install self reviewer agent files");
}

async function assertOrdinaryFullOpencodeInitRetainsAdvancedCommands() {
  await fs.rm(ordinaryFullOpencodeProject, { recursive: true, force: true });
  const output = await harness("init", "--project", ordinaryFullOpencodeProject, "--auto", "--with-opencode", "--opencode-command-surface", "full");
  assertIncludes(output, "new-managed: .opencode/commands/harness-feature.md");
  for (const command of advancedOpencodeCommands) {
    assert(await pathExists(path.join(ordinaryFullOpencodeProject, ".opencode", "commands", command)), `ordinary full init must install ${command}`);
  }
  assert(!(await pathExists(path.join(ordinaryFullOpencodeProject, ".opencode", "commands", "harness-self-init.md"))), "ordinary full init must not install self command files");

  const doctorOutput = await harness("doctor", "--project", ordinaryFullOpencodeProject);
  assertIncludes(doctorOutput, "PASS  OpenCode command surface [full] required normal commands present");
  assertIncludes(doctorOutput, "PASS  OpenCode command surface [full] advanced commands present");
}

async function getExpectedMirrorFiles() {
  const relativeFiles = [];
  for (const root of ["agents", "commands"]) {
    await collectRelativeFiles(path.join(repoRoot, "templates", "opencode", root), `.opencode/${root}`, relativeFiles);
  }
  relativeFiles.sort();
  return relativeFiles;
}

async function collectRelativeFiles(sourceDirectory, targetPrefix, relativeFiles) {
  const children = await fs.readdir(sourceDirectory, { withFileTypes: true });
  for (const child of children) {
    const childSource = path.join(sourceDirectory, child.name);
    const childTarget = `${targetPrefix}/${child.name}`;
    if (child.isDirectory()) {
      await collectRelativeFiles(childSource, childTarget, relativeFiles);
      continue;
    }
    if (child.isFile()) {
      relativeFiles.push(childTarget);
    }
  }
}

async function readExistingFiles(relativeFiles) {
  const entries = [];
  for (const relative of relativeFiles) {
    const absolute = path.join(repoRoot, relative);
    entries.push([relative, await pathExists(absolute) ? await fs.readFile(absolute, "utf8") : null]);
  }
  return entries;
}

async function readRelative(relative) {
  return fs.readFile(path.join(repoRoot, relative), "utf8");
}

async function snapshotDirectory(directoryPath) {
  const entries = [];
  await collectFiles(directoryPath, "", entries);
  return entries;
}

async function collectFiles(directoryPath, relativePrefix, entries) {
  const children = await fs.readdir(directoryPath, { withFileTypes: true });
  for (const child of children) {
    const childAbsolute = path.join(directoryPath, child.name);
    const childRelative = relativePrefix ? `${relativePrefix}/${child.name}` : child.name;
    if (child.isDirectory()) {
      await collectFiles(childAbsolute, childRelative, entries);
      continue;
    }
    entries.push([childRelative, await fs.readFile(childAbsolute, "utf8")]);
  }
  entries.sort(([left], [right]) => left.localeCompare(right));
  return entries;
}

async function pathExists(filePath) {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function assert(condition, message) {
  if (!condition) {
    throw new Error(message);
  }
}

function assertIncludes(content, expected) {
  assert(content.includes(expected), `Expected output to include: ${expected}\nActual output:\n${content}`);
}

function assertSameFileSnapshot(left, right, message) {
  assert(JSON.stringify(left) === JSON.stringify(right), message);
}

function assertExcludes(content, unexpected) {
  assert(!content.includes(unexpected), `Expected output to exclude: ${unexpected}\nActual output:\n${content}`);
}
